package com.example.dailytrack_mobile.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object YellowThemeColors {
    val lightScheme = lightColorScheme(
    primary = Color(0xFF676014),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFEFE58B),
    onPrimaryContainer = Color(0xFF4E4800),
    secondary = Color(0xFF635F41),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEAE3BE),
    onSecondaryContainer = Color(0xFF4B482C),
    tertiary = Color(0xFF406653),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC1ECD4),
    onTertiaryContainer = Color(0xFF284E3C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFEF9EB),
    onBackground = Color(0xFF1D1C14),
    surface = Color(0xFFFEF9EB),
    onSurface = Color(0xFF1D1C14),
    surfaceVariant = Color(0xFFE7E3D0),
    onSurfaceVariant = Color(0xFF49473A),
    outline = Color(0xFF7A7768),
    outlineVariant = Color(0xFFCBC7B5),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF323128),
    inverseOnSurface = Color(0xFFF5F0E3),
    inversePrimary = Color(0xFFD2C972),
    surfaceDim = Color(0xFFDEDACC),
    surfaceBright = Color(0xFFFEF9EB),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF8F3E6),
    surfaceContainer = Color(0xFFF2EEE0),
    surfaceContainerHigh = Color(0xFFEDE8DA),
    surfaceContainerHighest = Color(0xFFE7E2D5),
)

    val darkScheme = darkColorScheme(
    primary = Color(0xFFD2C972),
    onPrimary = Color(0xFF353100),
    primaryContainer = Color(0xFF4E4800),
    onPrimaryContainer = Color(0xFFEFE58B),
    secondary = Color(0xFFCDC7A3),
    onSecondary = Color(0xFF343117),
    secondaryContainer = Color(0xFF4B482C),
    onSecondaryContainer = Color(0xFFEAE3BE),
    tertiary = Color(0xFFA6D0B9),
    onTertiary = Color(0xFF0F3727),
    tertiaryContainer = Color(0xFF284E3C),
    onTertiaryContainer = Color(0xFFC1ECD4),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF15140C),
    onBackground = Color(0xFFE7E2D5),
    surface = Color(0xFF15140C),
    onSurface = Color(0xFFE7E2D5),
    surfaceVariant = Color(0xFF49473A),
    onSurfaceVariant = Color(0xFFCBC7B5),
    outline = Color(0xFF949181),
    outlineVariant = Color(0xFF49473A),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE7E2D5),
    inverseOnSurface = Color(0xFF323128),
    inversePrimary = Color(0xFF676014),
    surfaceDim = Color(0xFF15140C),
    surfaceBright = Color(0xFF3B3930),
    surfaceContainerLowest = Color(0xFF0F0E07),
    surfaceContainerLow = Color(0xFF1D1C14),
    surfaceContainer = Color(0xFF212017),
    surfaceContainerHigh = Color(0xFF2C2A21),
    surfaceContainerHighest = Color(0xFF37352C),
)
}
object GreenThemeColors {
    val lightScheme = lightColorScheme(
    primary = Color(0xFF4F6629),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD0EDA0),
    onPrimaryContainer = Color(0xFF384D13),
    secondary = Color(0xFF596248),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDDE6C6),
    onSecondaryContainer = Color(0xFF414A32),
    tertiary = Color(0xFF396661),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCECE6),
    onTertiaryContainer = Color(0xFF1F4E4A),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFAFAEE),
    onBackground = Color(0xFF1A1C15),
    surface = Color(0xFFFAFAEE),
    onSurface = Color(0xFF1A1C15),
    surfaceVariant = Color(0xFFE1E4D4),
    onSurfaceVariant = Color(0xFF45483D),
    outline = Color(0xFF75786C),
    outlineVariant = Color(0xFFC5C8B9),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2F312A),
    inverseOnSurface = Color(0xFFF1F2E6),
    inversePrimary = Color(0xFFB5D087),
    surfaceDim = Color(0xFFDADBCF),
    surfaceBright = Color(0xFFFAFAEE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F4E9),
    surfaceContainer = Color(0xFFEEEFE3),
    surfaceContainerHigh = Color(0xFFE8E9DD),
    surfaceContainerHighest = Color(0xFFE3E3D8),
)

    val darkScheme = darkColorScheme(
    primary = Color(0xFFB5D087),
    onPrimary = Color(0xFF223600),
    primaryContainer = Color(0xFF384D13),
    onPrimaryContainer = Color(0xFFD0EDA0),
    secondary = Color(0xFFC1CAAB),
    onSecondary = Color(0xFF2B331D),
    secondaryContainer = Color(0xFF414A32),
    onSecondaryContainer = Color(0xFFDDE6C6),
    tertiary = Color(0xFFA0D0CA),
    onTertiary = Color(0xFF013733),
    tertiaryContainer = Color(0xFF1F4E4A),
    onTertiaryContainer = Color(0xFFBCECE6),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF12140E),
    onBackground = Color(0xFFE3E3D8),
    surface = Color(0xFF12140E),
    onSurface = Color(0xFFE3E3D8),
    surfaceVariant = Color(0xFF45483D),
    onSurfaceVariant = Color(0xFFC5C8B9),
    outline = Color(0xFF8F9285),
    outlineVariant = Color(0xFF45483D),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE3E3D8),
    inverseOnSurface = Color(0xFF2F312A),
    inversePrimary = Color(0xFF4F6629),
    surfaceDim = Color(0xFF12140E),
    surfaceBright = Color(0xFF383A32),
    surfaceContainerLowest = Color(0xFF0D0F09),
    surfaceContainerLow = Color(0xFF1A1C15),
    surfaceContainer = Color(0xFF1E2019),
    surfaceContainerHigh = Color(0xFF292B23),
    surfaceContainerHighest = Color(0xFF33362E),
)
}
object TealThemeColors {
    val lightScheme = lightColorScheme(
    primary = Color(0xFF006A68),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF9CF1EF),
    onPrimaryContainer = Color(0xFF00504F),
    secondary = Color(0xFF4A6362),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE8E6),
    onSecondaryContainer = Color(0xFF324B4A),
    tertiary = Color(0xFF4A607C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD2E4FF),
    onTertiaryContainer = Color(0xFF334863),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF4FBF9),
    onBackground = Color(0xFF161D1C),
    surface = Color(0xFFF4FBF9),
    onSurface = Color(0xFF161D1C),
    surfaceVariant = Color(0xFFDAE5E3),
    onSurfaceVariant = Color(0xFF3F4948),
    outline = Color(0xFF6F7978),
    outlineVariant = Color(0xFFBEC9C7),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2B3231),
    inverseOnSurface = Color(0xFFECF2F1),
    inversePrimary = Color(0xFF80D5D2),
    surfaceDim = Color(0xFFD5DBDA),
    surfaceBright = Color(0xFFF4FBF9),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5F4),
    surfaceContainer = Color(0xFFE9EFEE),
    surfaceContainerHigh = Color(0xFFE3E9E8),
    surfaceContainerHighest = Color(0xFFDDE4E3),
)

    val darkScheme = darkColorScheme(
    primary = Color(0xFF80D5D2),
    onPrimary = Color(0xFF003736),
    primaryContainer = Color(0xFF00504F),
    onPrimaryContainer = Color(0xFF9CF1EF),
    secondary = Color(0xFFB0CCCA),
    onSecondary = Color(0xFF1B3534),
    secondaryContainer = Color(0xFF324B4A),
    onSecondaryContainer = Color(0xFFCCE8E6),
    tertiary = Color(0xFFB2C8E8),
    onTertiary = Color(0xFF1B324B),
    tertiaryContainer = Color(0xFF334863),
    onTertiaryContainer = Color(0xFFD2E4FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E1514),
    onBackground = Color(0xFFDDE4E3),
    surface = Color(0xFF0E1514),
    onSurface = Color(0xFFDDE4E3),
    surfaceVariant = Color(0xFF3F4948),
    onSurfaceVariant = Color(0xFFBEC9C7),
    outline = Color(0xFF889392),
    outlineVariant = Color(0xFF3F4948),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDDE4E3),
    inverseOnSurface = Color(0xFF2B3231),
    inversePrimary = Color(0xFF006A68),
    surfaceDim = Color(0xFF0E1514),
    surfaceBright = Color(0xFF343A3A),
    surfaceContainerLowest = Color(0xFF090F0F),
    surfaceContainerLow = Color(0xFF161D1C),
    surfaceContainer = Color(0xFF1A2120),
    surfaceContainerHigh = Color(0xFF252B2B),
    surfaceContainerHighest = Color(0xFF2F3636),
)
}
object PurpleThemeColors {
    val lightScheme = lightColorScheme(
    primary = Color(0xFF69548D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFECDCFF),
    onPrimaryContainer = Color(0xFF513C74),
    secondary = Color(0xFF635B70),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEADEF7),
    onSecondaryContainer = Color(0xFF4B4357),
    tertiary = Color(0xFF7F525C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9E0),
    onTertiaryContainer = Color(0xFF643B45),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFEF7FF),
    onBackground = Color(0xFF1D1A20),
    surface = Color(0xFFFEF7FF),
    onSurface = Color(0xFF1D1A20),
    surfaceVariant = Color(0xFFE8E0EB),
    onSurfaceVariant = Color(0xFF49454E),
    outline = Color(0xFF7A757F),
    outlineVariant = Color(0xFFCBC4CF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF322F35),
    inverseOnSurface = Color(0xFFF5EEF7),
    inversePrimary = Color(0xFFD4BBFC),
    surfaceDim = Color(0xFFDED8E0),
    surfaceBright = Color(0xFFFEF7FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF8F1F9),
    surfaceContainer = Color(0xFFF3ECF4),
    surfaceContainerHigh = Color(0xFFEDE6EE),
    surfaceContainerHighest = Color(0xFFE7E0E8),
)

    val darkScheme = darkColorScheme(
    primary = Color(0xFFD4BBFC),
    onPrimary = Color(0xFF3A255B),
    primaryContainer = Color(0xFF513C74),
    onPrimaryContainer = Color(0xFFECDCFF),
    secondary = Color(0xFFCEC2DB),
    onSecondary = Color(0xFF342D40),
    secondaryContainer = Color(0xFF4B4357),
    onSecondaryContainer = Color(0xFFEADEF7),
    tertiary = Color(0xFFF1B7C4),
    onTertiary = Color(0xFF4A252F),
    tertiaryContainer = Color(0xFF643B45),
    onTertiaryContainer = Color(0xFFFFD9E0),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF151218),
    onBackground = Color(0xFFE7E0E8),
    surface = Color(0xFF151218),
    onSurface = Color(0xFFE7E0E8),
    surfaceVariant = Color(0xFF49454E),
    onSurfaceVariant = Color(0xFFCBC4CF),
    outline = Color(0xFF958E99),
    outlineVariant = Color(0xFF49454E),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE7E0E8),
    inverseOnSurface = Color(0xFF322F35),
    inversePrimary = Color(0xFF69548D),
    surfaceDim = Color(0xFF151218),
    surfaceBright = Color(0xFF3B383E),
    surfaceContainerLowest = Color(0xFF0F0D12),
    surfaceContainerLow = Color(0xFF1D1A20),
    surfaceContainer = Color(0xFF211E24),
    surfaceContainerHigh = Color(0xFF2C292F),
    surfaceContainerHighest = Color(0xFF37343A),
)
}

object JuneOledThemeColors {
    val lightScheme = lightColorScheme(
        primary = Color(0xFF6750A4),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEADDFF),
        onPrimaryContainer = Color(0xFF21005D),
        secondary = Color(0xFF625B71),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE8DEF8),
        onSecondaryContainer = Color(0xFF1D192B),
        tertiary = Color(0xFF7D5260),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFD8E4),
        onTertiaryContainer = Color(0xFF31111D),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        background = Color(0xFFFEF7FF),
        onBackground = Color(0xFF1D1B20),
        surface = Color(0xFFFEF7FF),
        onSurface = Color(0xFF1D1B20),
        surfaceVariant = Color(0xFFE7E0EC),
        onSurfaceVariant = Color(0xFF49454F),
        outline = Color(0xFF79747E),
        outlineVariant = Color(0xFFCAC4D0),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF313033),
        inverseOnSurface = Color(0xFFF4EFF4),
        inversePrimary = Color(0xFFD0BCFF),
        surfaceDim = Color(0xFFDED8E1),
        surfaceBright = Color(0xFFFEF7FF),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7F2FA),
        surfaceContainer = Color(0xFFF3EDF7),
        surfaceContainerHigh = Color(0xFFECE6F0),
        surfaceContainerHighest = Color(0xFFE6E0E9),
    )

    val darkScheme = darkColorScheme(
        primary = Color(0xFFD0BCFF),
        onPrimary = Color(0xFF381E72),
        primaryContainer = Color(0xFF4F378B),
        onPrimaryContainer = Color(0xFFEADDFF),
        secondary = Color(0xFFCCC2DC),
        onSecondary = Color(0xFF332D41),
        secondaryContainer = Color(0xFF4A4458),
        onSecondaryContainer = Color(0xFFE8DEF8),
        tertiary = Color(0xFFEFB8C8),
        onTertiary = Color(0xFF492532),
        tertiaryContainer = Color(0xFF633B48),
        onTertiaryContainer = Color(0xFFFFD8E4),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        background = Color(0xFF000000),
        onBackground = Color(0xFFE6E0E9),
        surface = Color(0xFF000000),
        onSurface = Color(0xFFE6E0E9),
        surfaceVariant = Color(0xFF49454F),
        onSurfaceVariant = Color(0xFFCAC4D0),
        outline = Color(0xFF938F99),
        outlineVariant = Color(0xFF49454F),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE6E0E9),
        inverseOnSurface = Color(0xFF313033),
        inversePrimary = Color(0xFF6750A4),
        surfaceDim = Color(0xFF000000),
        surfaceBright = Color(0xFF242424),
        surfaceContainerLowest = Color(0xFF000000),
        surfaceContainerLow = Color(0xFF0D0D0D),
        surfaceContainer = Color(0xFF141414),
        surfaceContainerHigh = Color(0xFF1E1E1E),
        surfaceContainerHighest = Color(0xFF282828),
    )
}

object DtOgThemeColors {
    val lightScheme = lightColorScheme(
        primary = Color(0xFF4F46E5),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE0E7FF),
        onPrimaryContainer = Color(0xFF312E81),
        secondary = Color(0xFF0891B2),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFCFFAFE),
        onSecondaryContainer = Color(0xFF164E63),
        tertiary = Color(0xFF7C3AED),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFEDE9FE),
        onTertiaryContainer = Color(0xFF4C1D95),
        error = Color(0xFFDC2626),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFEE2E2),
        onErrorContainer = Color(0xFF991B1B),
        background = Color(0xFFEEF2F6),
        onBackground = Color(0xFF1E293B),
        surface = Color(0xFFEEF2F6),
        onSurface = Color(0xFF1E293B),
        surfaceVariant = Color(0xFFE3E8EF),
        onSurfaceVariant = Color(0xFF475569),
        outline = Color(0xFF94A3B8),
        outlineVariant = Color(0xFFCBD5E1),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF1E293B),
        inverseOnSurface = Color(0xFFEEF2F6),
        inversePrimary = Color(0xFFA5B4FC),
        surfaceDim = Color(0xFFD3DCE6),
        surfaceBright = Color(0xFFF8FAFC),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF8FAFC),
        surfaceContainer = Color(0xFFF1F5F9),
        surfaceContainerHigh = Color(0xFFF8FAFC),
        surfaceContainerHighest = Color(0xFFE3E8EF),
    )

    val darkScheme = darkColorScheme(
        primary = Color(0xFF818CF8),
        onPrimary = Color(0xFF0F0A38),
        primaryContainer = Color(0xFF312E81),
        onPrimaryContainer = Color(0xFFE0E7FF),
        secondary = Color(0xFF22D3EE),
        onSecondary = Color(0xFF00363D),
        secondaryContainer = Color(0xFF155E75),
        onSecondaryContainer = Color(0xFFCFFAFE),
        tertiary = Color(0xFFA78BFA),
        onTertiary = Color(0xFF2E1065),
        tertiaryContainer = Color(0xFF4C1D95),
        onTertiaryContainer = Color(0xFFDDD6FE),
        error = Color(0xFFF87171),
        onError = Color(0xFF450A0A),
        errorContainer = Color(0xFF7F1D1D),
        onErrorContainer = Color(0xFFFECACA),
        background = Color(0xFF080B12),
        onBackground = Color(0xFFE2E8F0),
        surface = Color(0xFF080B12),
        onSurface = Color(0xFFE2E8F0),
        surfaceVariant = Color(0xFF1A2235),
        onSurfaceVariant = Color(0xFF94A3B8),
        outline = Color(0xFF334155),
        outlineVariant = Color(0xFF1E293B),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFE2E8F0),
        inverseOnSurface = Color(0xFF080B12),
        inversePrimary = Color(0xFF4F46E5),
        surfaceDim = Color(0xFF080B12),
        surfaceBright = Color(0xFF222B3D),
        surfaceContainerLowest = Color(0xFF05070B),
        surfaceContainerLow = Color(0xFF0D1117),
        surfaceContainer = Color(0xFF111827),
        surfaceContainerHigh = Color(0xFF111827),
        surfaceContainerHighest = Color(0xFF1A2235),
    )
}

// Miles Morales — the Brooklyn suit: near-black ground, the red of the
// webbing as primary, and the electric violet of his venom-strike as the
// secondary accent, with a graffiti cyan for tertiary. Built dark-first;
// the light scheme keeps the same red/violet pairing on a bone ground.
object MilesMoralesThemeColors {
    val lightScheme = lightColorScheme(
        primary = Color(0xFFB3001F),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD9),
        onPrimaryContainer = Color(0xFF410007),
        secondary = Color(0xFF6B3FD4),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE7DBFF),
        onSecondaryContainer = Color(0xFF24005B),
        tertiary = Color(0xFF006876),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFB8F5FF),
        onTertiaryContainer = Color(0xFF001F25),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF8F7),
        onBackground = Color(0xFF201A1B),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF201A1B),
        surfaceVariant = Color(0xFFF4DDDD),
        onSurfaceVariant = Color(0xFF524343),
        outline = Color(0xFF857372),
        outlineVariant = Color(0xFFD8C1C1),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF362F2F),
        inverseOnSurface = Color(0xFFFBEEED),
        inversePrimary = Color(0xFFFFB3AE),
        surfaceDim = Color(0xFFE3D7D6),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFDF0EF),
        surfaceContainer = Color(0xFFF7EAE9),
        surfaceContainerHigh = Color(0xFFF1E4E3),
        surfaceContainerHighest = Color(0xFFEBDEDE),
    )

    val darkScheme = darkColorScheme(
        primary = Color(0xFFFF2E4D),
        onPrimary = Color(0xFF400009),
        primaryContainer = Color(0xFF8E0018),
        onPrimaryContainer = Color(0xFFFFDAD9),
        secondary = Color(0xFF9D6BFF),
        onSecondary = Color(0xFF2A0F5C),
        secondaryContainer = Color(0xFF45227F),
        onSecondaryContainer = Color(0xFFE7DBFF),
        tertiary = Color(0xFF3FE0F5),
        onTertiary = Color(0xFF00363D),
        tertiaryContainer = Color(0xFF004E5A),
        onTertiaryContainer = Color(0xFFB8F5FF),
        error = Color(0xFFFF6B6B),
        onError = Color(0xFF450000),
        errorContainer = Color(0xFF6B0000),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF0B0A0C),
        onBackground = Color(0xFFEDE6E7),
        surface = Color(0xFF0B0A0C),
        onSurface = Color(0xFFEDE6E7),
        surfaceVariant = Color(0xFF3A2E30),
        onSurfaceVariant = Color(0xFFD5C2C4),
        outline = Color(0xFF9E8A8C),
        outlineVariant = Color(0xFF4E3F41),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEDE6E7),
        inverseOnSurface = Color(0xFF2A2426),
        inversePrimary = Color(0xFFB3001F),
        surfaceDim = Color(0xFF0B0A0C),
        surfaceBright = Color(0xFF322A2C),
        surfaceContainerLowest = Color(0xFF050405),
        surfaceContainerLow = Color(0xFF151113),
        surfaceContainer = Color(0xFF1A1517),
        surfaceContainerHigh = Color(0xFF241E20),
        surfaceContainerHighest = Color(0xFF2F272A),
    )
}

// Synthwave — 80s neon on a deep violet night: hot magenta primary, neon
// cyan secondary, sunset amber tertiary. The loudest scheme of the set on
// purpose; the light mode deepens the same three hues to hold contrast.
object SynthwaveThemeColors {
    val lightScheme = lightColorScheme(
        primary = Color(0xFFB4006B),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFD8E8),
        onPrimaryContainer = Color(0xFF3D0022),
        secondary = Color(0xFF006A70),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFA8F6F9),
        onSecondaryContainer = Color(0xFF002023),
        tertiary = Color(0xFF8A5100),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFFDDB0),
        onTertiaryContainer = Color(0xFF2C1700),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFFF7FB),
        onBackground = Color(0xFF201A23),
        surface = Color(0xFFFFF7FB),
        onSurface = Color(0xFF201A23),
        surfaceVariant = Color(0xFFEDE0EE),
        onSurfaceVariant = Color(0xFF4D444E),
        outline = Color(0xFF7F747F),
        outlineVariant = Color(0xFFD0C3D1),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF352E37),
        inverseOnSurface = Color(0xFFFAEDF8),
        inversePrimary = Color(0xFFFFAFD3),
        surfaceDim = Color(0xFFE3D7E2),
        surfaceBright = Color(0xFFFFF7FB),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFDF0F8),
        surfaceContainer = Color(0xFFF7EAF2),
        surfaceContainerHigh = Color(0xFFF1E4ED),
        surfaceContainerHighest = Color(0xFFEBDEE7),
    )

    val darkScheme = darkColorScheme(
        primary = Color(0xFFFF3EA5),
        onPrimary = Color(0xFF4A0027),
        primaryContainer = Color(0xFF6E0040),
        onPrimaryContainer = Color(0xFFFFD8E8),
        secondary = Color(0xFF2DE2E6),
        onSecondary = Color(0xFF00363A),
        secondaryContainer = Color(0xFF004F54),
        onSecondaryContainer = Color(0xFFA8F6F9),
        tertiary = Color(0xFFFFB03A),
        onTertiary = Color(0xFF3D2600),
        tertiaryContainer = Color(0xFF5A3900),
        onTertiaryContainer = Color(0xFFFFDDB0),
        error = Color(0xFFFF5F6D),
        onError = Color(0xFF450000),
        errorContainer = Color(0xFF6B0012),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1A1033),
        onBackground = Color(0xFFEDE4FF),
        surface = Color(0xFF1A1033),
        onSurface = Color(0xFFEDE4FF),
        surfaceVariant = Color(0xFF3B2C57),
        onSurfaceVariant = Color(0xFFCFC1E8),
        outline = Color(0xFF9385B0),
        outlineVariant = Color(0xFF4A3A68),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEDE4FF),
        inverseOnSurface = Color(0xFF2B1F46),
        inversePrimary = Color(0xFFB4006B),
        surfaceDim = Color(0xFF1A1033),
        surfaceBright = Color(0xFF3D2F5C),
        surfaceContainerLowest = Color(0xFF0F0820),
        surfaceContainerLow = Color(0xFF20153C),
        surfaceContainer = Color(0xFF261A45),
        surfaceContainerHigh = Color(0xFF31234F),
        surfaceContainerHighest = Color(0xFF3C2C5C),
    )
}

// Faithful to the official Catppuccin palette (catppuccin.com) — Mocha for
// dark, its official Latte companion for light, so both modes are authentic
// rather than one side being improvised.
object CatppuccinMochaThemeColors {
    val lightScheme = lightColorScheme(
        primary = Color(0xFF8839EF),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFEDE0FC),
        onPrimaryContainer = Color(0xFF2E1854),
        secondary = Color(0xFF1E66F5),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDCE6FE),
        onSecondaryContainer = Color(0xFF0B2757),
        tertiary = Color(0xFFEA76CB),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFCE0F4),
        onTertiaryContainer = Color(0xFF4A1240),
        error = Color(0xFFD20F39),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFBD6DD),
        onErrorContainer = Color(0xFF4C0316),
        background = Color(0xFFEFF1F5),
        onBackground = Color(0xFF4C4F69),
        surface = Color(0xFFEFF1F5),
        onSurface = Color(0xFF4C4F69),
        surfaceVariant = Color(0xFFCCD0DA),
        onSurfaceVariant = Color(0xFF6C6F85),
        outline = Color(0xFF8C8FA1),
        outlineVariant = Color(0xFFBCC0CC),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF4C4F69),
        inverseOnSurface = Color(0xFFEFF1F5),
        inversePrimary = Color(0xFFCBA6F7),
        surfaceDim = Color(0xFFDBDEE8),
        surfaceBright = Color(0xFFEFF1F5),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFE9EBF1),
        surfaceContainer = Color(0xFFE4E6ED),
        surfaceContainerHigh = Color(0xFFDEE1E8),
        surfaceContainerHighest = Color(0xFFD8DBE3),
    )

    val darkScheme = darkColorScheme(
        primary = Color(0xFFCBA6F7),
        onPrimary = Color(0xFF2A1E42),
        primaryContainer = Color(0xFF43325F),
        onPrimaryContainer = Color(0xFFE6D9FA),
        secondary = Color(0xFF89B4FA),
        onSecondary = Color(0xFF0E2749),
        secondaryContainer = Color(0xFF243E63),
        onSecondaryContainer = Color(0xFFD3E2FE),
        tertiary = Color(0xFFF5C2E7),
        onTertiary = Color(0xFF4A2242),
        tertiaryContainer = Color(0xFF63375A),
        onTertiaryContainer = Color(0xFFFCE3F6),
        error = Color(0xFFF38BA8),
        onError = Color(0xFF4A0E1C),
        errorContainer = Color(0xFF63182B),
        onErrorContainer = Color(0xFFFCD9E1),
        background = Color(0xFF1E1E2E),
        onBackground = Color(0xFFCDD6F4),
        surface = Color(0xFF1E1E2E),
        onSurface = Color(0xFFCDD6F4),
        surfaceVariant = Color(0xFF313244),
        onSurfaceVariant = Color(0xFFA6ADC8),
        outline = Color(0xFF7F849C),
        outlineVariant = Color(0xFF45475A),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFCDD6F4),
        inverseOnSurface = Color(0xFF1E1E2E),
        inversePrimary = Color(0xFF7C5CB0),
        surfaceDim = Color(0xFF1E1E2E),
        surfaceBright = Color(0xFF3B3D53),
        surfaceContainerLowest = Color(0xFF11111B),
        surfaceContainerLow = Color(0xFF181825),
        surfaceContainer = Color(0xFF242536),
        surfaceContainerHigh = Color(0xFF2C2E40),
        surfaceContainerHighest = Color(0xFF37394D),
    )
}

object DtOgChartColors {
    val PieColors = listOf(
        Color(0xFF6366F1), // Indigo (DailyTrack web accent)
        Color(0xFF8B5CF6), // Purple
        Color(0xFFD946EF), // Fuchsia
        Color(0xFFEC4899), // Pink
        Color(0xFFF43F5E), // Rose
        Color(0xFFF97316), // Orange
        Color(0xFFEAB308), // Yellow
        Color(0xFF84CC16), // Lime
        Color(0xFF22C55E), // Green
        Color(0xFF10B981), // Emerald
        Color(0xFF14B8A6), // Teal
        Color(0xFF06B6D4)  // Cyan
    )
}

